# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#

---
include:
  # RESET
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view settings_reset
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: lily58_left_niceview_reset
  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view settings_reset
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: lily58_right_niceview_reset
  - board: seeeduino_xiao_ble
    shield: lily58_dongle settings_reset
    # snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: lily58_dongle_reset

  # STABLE
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: lily58_left_niceview
  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: lily58_right_niceview
  - board: seeeduino_xiao_ble
    shield: lily58_dongle
    # snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: lily58_dongle

  # DEBUG
  - board: seeeduino_xiao_ble
    shield: lily58_dongle
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: lily58_dongle_Debug






